name: Cypress Tests

on: push

jobs:
 build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Node
      #   uses: actions/setup-node@v2.1.2
      #   with:
      #     node-version: 18.14.0

      - name: Install packages
        run: npm run install --frozen-lockfile
      # Build app
      - name: Build App
        run: npm run build
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: the-build
          if-no-files-found: error
          path: build
          retention-days: 1
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [0, 1]
    steps:
      - name: Download the build
        uses: actions/download-artifact@v2
        with:
          name: the-build
          path: build
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        run: npm run install --frozen-lockfile
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Determine Tests to Run
        id: check_commit_message
        run: |
          if git log --format=%B -n 1 $GITHUB_SHA | grep -q "\[skip-tests\]"; then
            echo "::set-output name=skip_tests::true"
          else
            echo "::set-output name=skip_tests::false"
          fi
        shell: bash
      
      - name: Cypress run
        if: steps.check_commit_message.outputs.skip_tests != 'true'
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          browser: chrome
          wait-on: http://localhost:4173
          command: node scripts/cypress-ci-run.js
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          THIS_RUNNER: ${{ matrix.containers }}
          TOTAL_RUNNERS: 2
  after_success:
    needs: cypress-run
    runs-on: ubuntu-22.04
    if: ${{ needs.cypress-run.result == 'success' }}
    steps:
      - name: success
        uses: actions/github-script@v6
        with:
          script: |
            const result = 200
