name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Determine Tests to Run
        id: check_commit_message
        run: |
          if git log --format=%B -n 1 $GITHUB_SHA | grep -q "\[skip-tests\]"; then
            echo "::set-output name=skip_tests::true"
          else
            echo "::set-output name=skip_tests::false"
          fi
        shell: bash
      
      - name: Cypress run
        if: steps.check_commit_message.outputs.skip_tests != 'true'
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run preview
          browser: chrome
          wait-on: http://localhost:4173
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  after_success:
    needs: cypress-run
    runs-on: ubuntu-22.04
    if: ${{ needs.cypress-run.result == 'success' }}
    steps:
      - name: success
        uses: actions/github-script@v6
        with:
          script: |
            const result = 200
