name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run preview
          browser: chrome
          wait-on: http://localhost:4173
  after_success:
    runs-on: ubuntu-22.04
    steps:
      - name: success
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const result = 200
            fs.writeFileSync(path.resolve(__dirname, 'result.txt'), result)
